<?php
declare(strict_types=1);

namespace Q\Expression;

use Q\IExpression;
use Q\IProvider;

/**
 * Interface for abstract SQL "DROP" Expressions.
 *
 * @package Q
 * @author  Kerry <Q@DevelopmentHero.de>
 */
interface IInsert extends IExpression {

    /**
     * Initializes a new instance of the IInsert class.
     *
     * @param \Q\IProvider $Provider Initializes the IInsert with the specified Provider.
     */
    public function __construct(IProvider $Provider);

    /**
     * Applies a specified target table to the IInsert.
     *
     * @param string     $Table  The table to insert any values.
     * @param null|array $Fields The fields of multiple values to insert.
     *
     * @return \Q\Expression\IInsert The current instance for further chaining.
     */
    public function Into(string $Table, array $Fields = null): static;

    /**
     * Applies one or more fields and values to the IInsert.
     *
     * @param array $Values      The fields and values to insert.
     * @param array ...$Multiple Additional values to insert.
     *
     * @return \Q\Expression\IInsert The current instance for further chaining.
     */
    public function Values(array $Values, array ...$Multiple): static;

    /**
     * Executes the IInsert and retrieves the last insert ID.
     *
     * @return int Tha last insert ID generated by an auto incrementation column.
     */
    public function ID(): int;

}